logging:
  level:
    root: INFO
#modelFilename: "ggml-gpt4all-j-v1.3-groovy.bin"
modelFilename: "ggml-replit-code-v1-3b.bin"
modelBasePath: "C:\\Users\\felix\\AppData\\Local\\nomic.ai\\GPT4All\\"
llmDebugMode: true